# seed
random_seed: 1 

# data
dataset_type: 'spatio_temporal_data'
data_Y_tensor: '/Users/jiangxiaoyu/Desktop/All Projects/Scalable_LVMOGP/data/climate_data/tensors/temperature.pt'
data_lat_tensor: '/Users/jiangxiaoyu/Desktop/All Projects/Scalable_LVMOGP/data/climate_data/tensors/latitude.pt'
data_lon_tensor: '/Users/jiangxiaoyu/Desktop/All Projects/Scalable_LVMOGP/data/climate_data/tensors/longitude.pt'

# input
min_input_bound: 0 
max_input_bound: 10 

# model
n_outputs: 1131 # 1131
n_input: 363
n_input_train: 289  # # of train inputs for every output 
n_input_test: 74   #  # of test inputs for every output 
input_dim: 1
latent_dim: 2
n_inducing_input: 20
batch_size_input:  20
learn_inducing_locations_input: True
input_kernel_type: Scale_Matern52_plus_Scale_PeriodicInputsMatern52 

# model initialization
1stKernel_outputscale_init: 0.5
1stKernel_lengthscale_init: 1.
2ndKernel_outputscale_init: 0.5
2ndKernel_lengthscale_init: 1.
2ndKernel_period_init: 0.33
init_likelihood_noise: 0.05
init_inducing_input_LB: 0
init_inducing_input_UB: 10

# optimizer
lr: 0.01
step_size: 20
gamma: 0.95
# step_size_up: 30

# training
n_iterations: 5000
num_latent_MC: 3
model_max_grad_norm: 1
likeli_max_grad_norm: 0.1