# data
dataset_type: synthetic_regression
data_Y_squeezed_path: /Users/jiangxiaoyu/Desktop/All Projects/Scalable_LVMOGP/data/synth_regression/smartly_generated/ninputs_50_nlatents_2000/target_data.csv

# input
min_input_bound: 0 
max_input_bound: 20 

# model
n_outputs: 2000 
n_input: 50
n_input_train: 25  # # of train inputs for every output 
n_input_test: 25   #  # of test inputs for every output 
input_dim: 1
latent_dim: 2
n_inducing_input: 20
batch_size_input:  20
learn_inducing_locations_input: True
input_kernel_type: Scale_RBF 

# model initialization
# kernels using default initialization ... 
init_inducing_input_LB: 0
init_inducing_input_UB: 20
init_likelihood_noise: 0.05

# optimizer
lr: 0.01 # 0.01
step_size_up: 30

# training
n_iterations: 5000
model_max_grad_norm: 1
likeli_max_grad_norm: 0.1
