# seed
random_seed: 12

# data
dataset_type: 'spatio_temporal_data'
data_Y_tensor: '/Users/jiangxiaoyu/Desktop/All Projects/Scalable_LVMOGP/data/climate_data/tensors_1131_outputs/temperature.pt'
data_lat_tensor: '/Users/jiangxiaoyu/Desktop/All Projects/Scalable_LVMOGP/data/climate_data/tensors_1131_outputs/latitude.pt'
data_lon_tensor: '/Users/jiangxiaoyu/Desktop/All Projects/Scalable_LVMOGP/data/climate_data/tensors_1131_outputs/longitude.pt'

# input
min_input_bound: 0 
max_input_bound: 10 

# model
n_outputs: 1131 # 1131
n_input: 363
n_input_train: 289  # # of train inputs for every output 
n_input_test: 74   #  # of test inputs for every output 
input_dim: 1
latent_dim: 2
trainable_latent_dim: 0
NNEncoder: False
# (1) trainable_latent_dim = None: only 1 part, all trainable ; (but initialization need to be re-implement)
# (2) trainable_latent_dim = 0: only 1 part, all fixed ; 
# (3) 0 < trainable_latent_dim < latent_dim: 2 parts ; 
# (4) trainable_latent_dim = latent_dim: only 1 part, all trainable ; (together with random initialization)
n_inducing_input: 20
n_inducing_latent: 50
batch_size_latent: 50
batch_size_input:  20
pca: False
learn_inducing_locations_latent: True
learn_inducing_locations_input: True
latent_kernel_type: 'Scale_RBF'
input_kernel_type: Periodic_times_Scale_RBF 
beta: 1
alpha: 1

# model initialization
1stKernel_peirod_init: 0.33
1stKernel_lengthscale_init: 1.
2ndKernel_lengthscale_init: 20.
2ndKernel_outputscale_init: 1.
init_likelihood_noise: 0.05
init_inducing_input_LB: 0
init_inducing_input_UB: 10

# optimizer
lr: 0.01
step_size_up: 30

# training
n_iterations: 10000
num_latent_MC: 3
model_max_grad_norm: 1
likeli_max_grad_norm: 0.1